apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
  namespace: "yolo"
  labels:
    #Project ID
    app: yolo-backend
spec:
  ports:
    - nodePort: 32420
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: yolo-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  namespace: "yolo"
  labels:
    app: yolo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: yolo-backend
          image: Oyonka/yolo-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
        - name: nginx-2
          image: nginx:latest
          imagePullPolicy: Always
