apiVersion: v1
kind: Service
metadata:
  name: yolo-client-service
  namespace: "yolo"
  labels:
    #Project ID
    app: yolo-client
spec:
  ports:
    - nodePort: 32415
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: yolo-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
  namespace: "yolo"
  labels:
    app: yolo-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: yolo-client
          image: Oyonka/yolo-client:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
        - name: nginx-2
          image: nginx:latest
          imagePullPolicy: Always
