apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo-service
  namespace: "yolo"
  labels:
    #Project ID
    app: yolo-mongo
spec:
  ports:
    # - nodePort: 32425
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: yolo-mongo
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-mongo
  namespace: "yolo"
  labels:
    app: yolo-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-mongo
  template:
    metadata:
      labels:
        app: yolo-mongo
    spec:
      containers:
        - name: yolo-mongo
          image: Oyonka/mongoauth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
